# This workflow will install Python dependencies and run the script

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  schedule:
#    - cron: "* 23 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        HDX_KEY: ${{ secrets.HDX_KEY }}
        PREPREFIX: ${{ secrets.PREPREFIX }}
        GSHEET_AUTH: ${{ secrets.GSHEET_AUTH }}
        UPDATE_SHEETS: ${{ secrets.UPDATE_SHEETS }}
        BASIC_AUTH: ${{ secrets.BASIC_AUTH }}
      run: |
        python run.py
