# This workflow will install Python dependencies and run the script

name: run

on:
  workflow_dispatch: # add run button in github
  schedule:
    - cron: "00 8 * * *"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        HDX_KEY: ${{ secrets.HDX_KEY }}
        PREPREFIX: ${{ secrets.PREPREFIX }}
        GSHEET_AUTH: ${{ secrets.GSHEET_AUTH }}
        UPDATESHEETS: ${{ secrets.UPDATESHEETS }}
        BASIC_AUTHS: ${{ secrets.BASIC_AUTHS }}
        OTHER_AUTHS: ${{ secrets.OTHER_AUTHS }}
      run: |
        python run.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: Commit updated data bundle
      with:
        file_pattern: out*.json
        commit_message: automatic - Data bundle updated
        push_options: '--force'